#!/bin/bash

##########################

Author : Pavan

Date : 08/01/26

##########################

# Additioin 

x=$1+$2

# substraction


# division

# Percentage

Deemostrating rebase example

# Exponential 
New functionalit addeed

#Multiplication

This is testing advance topics such as merge and rebase 
